[package]
name = "bluescreen-example"
workspace = "../.."
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pybadge-high = { path = "../../pybadge-high", features = ["bluescreen-message-nightly"]}
