[package]
name = "pwm_sound"
workspace = "../.."
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
cortex-m-rt = "0.7.3"
embedded-graphics = "0.7.1"
heapless = "0.7.16"
pybadge-high = { path = "../../pybadge-high", features = ["pwm_sound"]  }
