[package]
name = "usb-interrupt-neopixel"
workspace = "../.."
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pybadge-high = { path = "../../pybadge-high",  features = ["neopixel", "usb"]  }
smart-leds = "0.3.0"
