[package]
name = "pybadge-high"
workspace = ".."
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
embedded-graphics = "0.7.1"
edgebadge = { version = "0.9.0"}
st7735-lcd = { version = "0.8.1", default-features = false }
